### PR TITLE
Add checking packet length in _irq_handler

### PR DESCRIPTION
**Pull request by przemobe**

### CODE REVIEW

**Review by xg590 — APPROVED** [review]

**Review by xg590 — COMMENTED** [review]
Are you trying to test the range of PacketSnr in new line 264?
Why not just add a new line before 264, which is simpler?
```
264 bytes([PacketSnr]) # make sure it is between 0~255
265 SNR        = PacketSnr / 4
```

**Comment by przemobe** [comment]
> 

No. Checking range is not necessary as ```self.spi_read()``` returns just value from a byte.
The idea is to cast the byte to signed integer.
For example: value 255 shall be interpreted as -1/4 = -0.25.
Currently we get 255/4 = 63.75 which is incorrect.
Please refer to page 122 of SX1276/77/78/79 Data Sheet:
"Estimation of SNR on last packet received. In two’s compliment format mutiplied by 4."

**Review by xg590 — APPROVED** [review]
Thanks for przemobe's correction!
According to the datasheet, SNR is calculated based on two's compliment format of PacketSnr. So the new formula is correct.

**Comment by xg590** [comment]
The old SNR is calculated based on a wrong formula. This right formula is in page 112 of [datasheet](https://github.com/xg590/Learn_SX1276/raw/main/Datasheet.pdf). 
```
SNR[dB] = PacketSnr[twos complement]/4

**Pull request merged**
